name: ðŸ“¦ Pull Request
on: [pull_request]
jobs:
  pullrequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Make envfile ðŸ”’
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          file_name: .env
      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn test
          yarn build
      - name: Deploy ðŸš€
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
          dist: build
          teardown: 'true'
          failOnError: true
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.ACCESS_TOKEN }}
          url: ${{ steps.preview_step.outputs.preview_url }}
          wptConnectionSpeed: threegfast
      - name: Saving Lighthouse Audit Artifacts
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-artifacts
          path: './results'